from __future__ import annotations

from ..xml import (
    XML_DECLARATION,
    append_element_items,
    append_items,
    append_text,
    append_value,
    bool_text,
    child_by_name,
    child_int,
    child_item_texts,
    child_item_values,
    child_text,
    child_value,
    children_by_name,
    coerce_enum_value,
    flag_text,
    item_texts,
    looks_like_xml,
    parse_bool,
    parse_flag_names,
    parse_xml_root,
    read_xml_text,
    xml_bytes,
)

__all__ = [
    "XML_DECLARATION",
    "append_element_items",
    "append_items",
    "append_text",
    "append_value",
    "bool_text",
    "child_by_name",
    "child_int",
    "child_item_texts",
    "child_item_values",
    "child_text",
    "child_value",
    "children_by_name",
    "coerce_enum_value",
    "flag_text",
    "item_texts",
    "looks_like_xml",
    "parse_bool",
    "parse_flag_names",
    "parse_xml_root",
    "read_xml_text",
    "xml_bytes",
]
