DEFAULT_YED_VERSION = 25
VIRTUAL_BASE = 0x50000000
ROOT_OFFSET = 0
DEFAULT_YED_DICTIONARY_VFT = 0x40573560
DEFAULT_YED_EXPRESSION_VFT = 0x40600000
EXPRESSION_BLOCK_SIZE = 0x90
SPRING_BLOCK_SIZE = 0xA0

__all__ = [
    "DEFAULT_YED_DICTIONARY_VFT",
    "DEFAULT_YED_EXPRESSION_VFT",
    "DEFAULT_YED_VERSION",
    "EXPRESSION_BLOCK_SIZE",
    "ROOT_OFFSET",
    "SPRING_BLOCK_SIZE",
    "VIRTUAL_BASE",
]
