DEFAULT_YED_VERSION = 25
VIRTUAL_BASE = 0x50000000
ROOT_OFFSET = 0
DEFAULT_YED_DICTIONARY_VFT = 0x40573540
DEFAULT_YED_EXPRESSION_VFT = 0x405A3548
EXPRESSION_BLOCK_SIZE = 0x90
SPRING_BLOCK_SIZE = 0xA0
YED_FACIAL_ROOT_BONE_ID = 65068
YED_FACIAL_ROOT_BONE_NAME = "FACIAL_facialRoot"

__all__ = [
    "DEFAULT_YED_DICTIONARY_VFT",
    "DEFAULT_YED_EXPRESSION_VFT",
    "DEFAULT_YED_VERSION",
    "EXPRESSION_BLOCK_SIZE",
    "ROOT_OFFSET",
    "SPRING_BLOCK_SIZE",
    "YED_FACIAL_ROOT_BONE_ID",
    "YED_FACIAL_ROOT_BONE_NAME",
    "VIRTUAL_BASE",
]
