CUT_FPS = 30.0
CUT_MINIMUM_DURATION_FRAMES = 30
CUT_MINIMUM_DURATION = CUT_MINIMUM_DURATION_FRAMES / CUT_FPS
CUT_MINIMUM_SECTION_DURATION = 1.0
CUT_MAX_CONCATENATED_SCENES = 40
CUT_MAX_PSO_ARRAY_ITEMS = 0xFFFF


__all__ = [
    "CUT_FPS",
    "CUT_MAX_CONCATENATED_SCENES",
    "CUT_MAX_PSO_ARRAY_ITEMS",
    "CUT_MINIMUM_DURATION",
    "CUT_MINIMUM_DURATION_FRAMES",
    "CUT_MINIMUM_SECTION_DURATION",
]
