from __future__ import annotations

from ..common import FlexibleIntEnum


class RelDatFileType(FlexibleIntEnum):
    DAT4 = 4
    DAT10_MODULAR_SYNTH = 10
    DAT15_DYNAMIC_MIXER = 15
    DAT16_CURVES = 16
    DAT22_CATEGORIES = 22
    DAT54_DATA_ENTRIES = 54
    DAT149 = 149
    DAT150 = 150
    DAT151 = 151


class Dat10RelType(FlexibleIntEnum):
    SYNTH_PRESET = 1
    SYNTH = 3


class Dat16RelType(FlexibleIntEnum):
    CONSTANT_CURVE = 1
    LINEAR_CURVE = 2
    LINEAR_DB_CURVE = 3
    PIECEWISE_LINEAR_CURVE = 4
    EQUAL_POWER_CURVE = 5
    VALUE_TABLE_CURVE = 6
    EXPONENTIAL_CURVE = 7
    DECAYING_EXPONENTIAL_CURVE = 8
    DECAYING_SQUARED_EXPONENTIAL_CURVE = 9
    SINE_CURVE = 10
    ONE_OVER_X_SQUARED_CURVE = 12
    DEFAULT_DISTANCE_ATTENUATION_CURVE = 13
    DISTANCE_ATTENUATION_VALUE_TABLE_CURVE = 15


class Dat22RelType(FlexibleIntEnum):
    CATEGORY = 0


class Dat54SoundType(FlexibleIntEnum):
    LOOPING_SOUND = 1
    ENVELOPE_SOUND = 2
    TWIN_LOOP_SOUND = 3
    SPEECH_SOUND = 4
    ON_STOP_SOUND = 5
    WRAPPER_SOUND = 6
    SEQUENTIAL_SOUND = 7
    STREAMING_SOUND = 8
    RETRIGGERED_OVERLAPPED_SOUND = 9
    CROSSFADE_SOUND = 10
    COLLAPSING_STEREO_SOUND = 11
    SIMPLE_SOUND = 12
    MULTITRACK_SOUND = 13
    RANDOMIZED_SOUND = 14
    ENVIRONMENT_SOUND = 15
    DYNAMIC_ENTITY_SOUND = 16
    SEQUENTIAL_OVERLAP_SOUND = 17
    MODULAR_SYNTH_SOUND = 18
    GRANULAR_SOUND = 19
    DIRECTIONAL_SOUND = 20
    KINETIC_SOUND = 21
    SWITCH_SOUND = 22
    VARIABLE_CURVE_SOUND = 23
    VARIABLE_PRINT_VALUE_SOUND = 24
    VARIABLE_BLOCK_SOUND = 25
    IF_SOUND = 26
    MATH_OPERATION_SOUND = 27
    PARAMETER_TRANSFORM_SOUND = 28
    FLUCTUATOR_SOUND = 29
    AUTOMATION_SOUND = 30
    EXTERNAL_STREAM_SOUND = 31
    SOUND_SET = 32
    AUTOMATION_NOTE_MAP_SOUND = 33
    SOUND_SET_LIST = 34
    SOUND_HASH_LIST = 35
