from __future__ import annotations

from ..common import FlexibleIntEnum


class RelDatFileType(FlexibleIntEnum):
    DAT4 = 4
    DAT10_MODULAR_SYNTH = 10
    DAT15_DYNAMIC_MIXER = 15
    DAT16_CURVES = 16
    DAT22_CATEGORIES = 22
    DAT54_DATA_ENTRIES = 54
    DAT149 = 149
    DAT150 = 150
    DAT151 = 151


class Dat4ConfigType(FlexibleIntEnum):
    INT = 0
    UNSIGNED_INT = 1
    FLOAT = 2
    STRING = 3
    VECTOR3 = 5
    VARIABLE_LIST = 7
    WAVE_SLOT = 8
    WAVE_SLOTS_LIST = 9
    ER_SETTINGS = 10


class Dat10RelType(FlexibleIntEnum):
    SYNTH_PRESET = 1
    SYNTH = 3


class Dat16RelType(FlexibleIntEnum):
    CONSTANT_CURVE = 1
    LINEAR_CURVE = 2
    LINEAR_DB_CURVE = 3
    PIECEWISE_LINEAR_CURVE = 4
    EQUAL_POWER_CURVE = 5
    VALUE_TABLE_CURVE = 6
    EXPONENTIAL_CURVE = 7
    DECAYING_EXPONENTIAL_CURVE = 8
    DECAYING_SQUARED_EXPONENTIAL_CURVE = 9
    SINE_CURVE = 10
    ONE_OVER_X_SQUARED_CURVE = 12
    DEFAULT_DISTANCE_ATTENUATION_CURVE = 13
    DISTANCE_ATTENUATION_VALUE_TABLE_CURVE = 15


class Dat22RelType(FlexibleIntEnum):
    CATEGORY = 0


class Dat54SoundType(FlexibleIntEnum):
    LOOPING_SOUND = 1
    ENVELOPE_SOUND = 2
    TWIN_LOOP_SOUND = 3
    SPEECH_SOUND = 4
    ON_STOP_SOUND = 5
    WRAPPER_SOUND = 6
    SEQUENTIAL_SOUND = 7
    STREAMING_SOUND = 8
    RETRIGGERED_OVERLAPPED_SOUND = 9
    CROSSFADE_SOUND = 10
    COLLAPSING_STEREO_SOUND = 11
    SIMPLE_SOUND = 12
    MULTITRACK_SOUND = 13
    RANDOMIZED_SOUND = 14
    ENVIRONMENT_SOUND = 15
    DYNAMIC_ENTITY_SOUND = 16
    SEQUENTIAL_OVERLAP_SOUND = 17
    MODULAR_SYNTH_SOUND = 18
    GRANULAR_SOUND = 19
    DIRECTIONAL_SOUND = 20
    KINETIC_SOUND = 21
    SWITCH_SOUND = 22
    VARIABLE_CURVE_SOUND = 23
    VARIABLE_PRINT_VALUE_SOUND = 24
    VARIABLE_BLOCK_SOUND = 25
    IF_SOUND = 26
    MATH_OPERATION_SOUND = 27
    PARAMETER_TRANSFORM_SOUND = 28
    FLUCTUATOR_SOUND = 29
    AUTOMATION_SOUND = 30
    EXTERNAL_STREAM_SOUND = 31
    SOUND_SET = 32
    AUTOMATION_NOTE_MAP_SOUND = 33
    SOUND_SET_LIST = 34
    SOUND_HASH_LIST = 35


class Dat151RelType(FlexibleIntEnum):
    VEHICLE_COLLISION_SETTINGS = 1
    TRAILER_AUDIO_SETTINGS = 2
    CAR_AUDIO_SETTINGS = 3
    VEHICLE_ENGINE_AUDIO_SETTINGS = 4
    COLLISION_MATERIAL_SETTINGS = 5
    STATIC_EMITTER = 6
    ENTITY_EMITTER = 7
    HELI_AUDIO_SETTINGS = 8
    MELEE_COMBAT_SETTINGS = 9
    SPEECH_CONTEXT_SETTINGS = 10
    TRIGGERED_SPEECH_CONTEXT = 11
    SPEECH_CONTEXT = 12
    SPEECH_CONTEXT_VIRTUAL = 13
    SPEECH_PARAMS = 14
    SPEECH_CONTEXT_LIST = 15
    BOAT_AUDIO_SETTINGS = 16
    WEAPON_SETTINGS = 17
    SHOE_AUDIO_SETTINGS = 18
    MODEL_PHYSICS_PARAMS = 22
    SKI_AUDIO_SETTINGS = 23
    RADIO_STATION_LIST = 24
    RADIO_STATION_SETTINGS = 25
    RADIO_STATION_TRACK_LIST = 26
    RADIO_TRACK_CATEGORY_DATA = 27
    SCANNER_CRIME_REPORT = 28
    PED_RACE_TO_PED_VOICE_GROUP = 29
    PED_VOICE_GROUPS = 30
    FRIEND_GROUP = 31
    STATIC_EMITTER_LIST = 32
    SCRIPTED_SCANNER_LINE = 33
    SCANNER_SPECIFIC_LOCATION = 35
    SCANNER_SPECIFIC_LOCATION_LIST = 36
    AMBIENT_ZONE = 37
    AMBIENT_RULE = 38
    AMBIENT_ZONE_LIST = 39
    AMBIENT_SLOT_MAP = 40
    AMBIENT_BANK_MAP = 41
    ENVIRONMENT_RULE = 42
    INTERIOR_SETTINGS = 44
    INTERIOR_WEAPON_METRICS = 45
    INTERIOR_ROOM = 46
    DOOR_AUDIO_SETTINGS = 47
    DOOR_TUNING_PARAMS = 48
    DOOR_LIST = 49
    ITEM_AUDIO_SETTINGS = 50
    CLIMBING_AUDIO_SETTINGS = 51
    MODEL_AUDIO_COLLISION_SETTINGS = 52
    TRAIN_AUDIO_SETTINGS = 53
    WEATHER_AUDIO_SETTINGS = 54
    WEATHER_TYPE_AUDIO_REFERENCE = 55
    BICYCLE_AUDIO_SETTINGS = 56
    PLANE_AUDIO_SETTINGS = 57
    STEM_MIX = 59
    INTERACTIVE_MUSIC_MOOD = 62
    START_TRACK_ACTION = 63
    STOP_TRACK_ACTION = 64
    SET_MOOD_ACTION = 65
    MUSIC_EVENT = 66
    START_ONE_SHOT_ACTION = 67
    STOP_ONE_SHOT_ACTION = 68
    BEAT_CONSTRAINT = 69
    BAR_CONSTRAINT = 70
    DIRECTIONAL_AMBIENCE = 71
    GUNFIGHT_CONDUCTOR_INTENSITY_SETTINGS = 72
    ANIMAL_PARAMS = 73
    ANIMAL_VOCAL_ANIM_TRIGGER = 74
    SCANNER_VOICE_PARAMS = 75
    SCANNER_VEHICLE_PARAMS = 76
    AUDIO_ROAD_INFO = 77
    MICROPHONE_SETTINGS_REFERENCE = 78
    MICROPHONE_SETTINGS = 79
    CAR_RECORDING_AUDIO_SETTINGS = 80
    CAR_RECORDING_LIST = 81
    ANIMAL_FOOTSTEP_SETTINGS = 82
    ANIMAL_FOOTSTEP_REFERENCE = 83
    SHOE_LIST = 84
    CLOTH_AUDIO_SETTINGS = 85
    CLOTH_LIST = 86
    EXPLOSION_AUDIO_SETTINGS = 87
    GRANULAR_ENGINE_AUDIO_SETTINGS = 88
    SHORE_LINE_POOL_AUDIO_SETTINGS = 90
    SHORE_LINE_LAKE_AUDIO_SETTINGS = 91
    SHORE_LINE_RIVER_AUDIO_SETTINGS = 92
    SHORE_LINE_OCEAN_AUDIO_SETTINGS = 93
    SHORE_LINE_LIST = 94
    RADIO_TRACK_SETTINGS = 95
    MODEL_FOOTSTEP_TUNING = 96
    RADIO_DJ_SPEECH_ACTION = 98
    SILENCE_CONSTRAINT = 99
    REFLECTIONS_SETTINGS = 100
    ALARM_SETTINGS = 101
    FADE_OUT_RADIO_ACTION = 102
    FADE_IN_RADIO_ACTION = 103
    FORCE_RADIO_TRACK_ACTION = 104
    SLOW_MO_SETTINGS = 105
    PED_SCENARIO_AUDIO_SETTINGS = 106
    PORTAL_SETTINGS = 107
    ELECTRIC_ENGINE_AUDIO_SETTINGS = 108
    PLAYER_BREATHING_SETTINGS = 109
    PED_WALLA_SPEECH_SETTINGS = 110
    AIRCRAFT_WARNING_SETTINGS = 111
    PED_WALLA_SPEECH_SETTINGS_LIST = 112
    COP_DISPATCH_INTERACTION_SETTINGS = 113
    RADIO_TRACK_TEXT_IDS = 114
    RANDOMISED_RADIO_EMITTER_SETTINGS = 115
    TENNIS_VOCALIZATION_SETTINGS = 116
    DOOR_AUDIO_SETTINGS_LINK = 117
    SPORTS_CAR_REVS_SETTINGS = 118
    FOLIAGE_SETTINGS = 119
    REPLAY_RADIO_STATION_TRACK_LIST = 120
    MODEL_AUDIO_COLLISION_SETTINGS_OVERRIDE_LIST = 121
    GAME_OBJECT_HASH_LIST = 124


class Dat151ZoneShape(FlexibleIntEnum):
    BOX = 0
    SPHERE = 1
    LINE = 2


class Dat151ExplicitSpawnType(FlexibleIntEnum):
    DISABLED = 0
    WORLD_RELATIVE = 1
    INTERIOR_RELATIVE = 2
