#include "py_bindings.h"

namespace fivefury_py {

PyMethodDef module_methods[] = {
    {"index_new", mod_index_new, METH_NOARGS, nullptr},
    {"index_clear", mod_index_clear, METH_VARARGS, nullptr},
    {"index_count", mod_index_count, METH_VARARGS, nullptr},
    {"index_add", mod_index_add, METH_VARARGS, nullptr},
    {"index_find_path_id", mod_index_find_path_id, METH_VARARGS, nullptr},
    {"index_find_hash_ids", mod_index_find_hash_ids, METH_VARARGS, nullptr},
    {"index_find_hashes_ids", mod_index_find_hashes_ids, METH_VARARGS, nullptr},
    {"index_find_kind_ids", mod_index_find_kind_ids, METH_VARARGS, nullptr},
    {"index_find_container_ids", mod_index_find_container_ids, METH_VARARGS, nullptr},
    {"index_find_stem_prefix_ids", mod_index_find_stem_prefix_ids, METH_VARARGS, nullptr},
    {"index_kind_short_hash_map", mod_index_kind_short_hash_map, METH_VARARGS, nullptr},
    {"index_kind_counts", mod_index_kind_counts, METH_VARARGS, nullptr},
    {"index_get_path", mod_index_get_path, METH_VARARGS, nullptr},
    {"index_export_paths", mod_index_export_paths, METH_VARARGS, nullptr},
    {"index_get_kind", mod_index_get_kind, METH_VARARGS, nullptr},
    {"index_get_size", mod_index_get_size, METH_VARARGS, nullptr},
    {"index_get_uncompressed_size", mod_index_get_uncompressed_size, METH_VARARGS, nullptr},
    {"index_get_flags", mod_index_get_flags, METH_VARARGS, nullptr},
    {"index_get_archive_encryption", mod_index_get_archive_encryption, METH_VARARGS, nullptr},
    {"index_get_name_hash", mod_index_get_name_hash, METH_VARARGS, nullptr},
    {"index_get_short_hash", mod_index_get_short_hash, METH_VARARGS, nullptr},
    {"index_export_state", mod_index_export_state, METH_VARARGS, nullptr},
    {"index_import_state", mod_index_import_state, METH_VARARGS, nullptr},
    {"meta_extract_ytyp_texture_relationships", mod_meta_extract_ytyp_texture_relationships, METH_VARARGS, nullptr},
    {"texture_index_new", mod_texture_index_new, METH_NOARGS, nullptr},
    {"texture_index_clear", mod_texture_index_clear, METH_VARARGS, nullptr},
    {"texture_index_count", mod_texture_index_count, METH_VARARGS, nullptr},
    {"texture_index_add", mod_texture_index_add, METH_VARARGS, nullptr},
    {"texture_index_add_many", mod_texture_index_add_many, METH_VARARGS, nullptr},
    {"texture_index_find_texture", mod_texture_index_find_texture, METH_VARARGS, nullptr},
    {"texture_index_find_dictionary", mod_texture_index_find_dictionary, METH_VARARGS, nullptr},
    {"crypto_new", mod_crypto_new, METH_VARARGS, nullptr},
    {"crypto_can_decrypt", mod_crypto_can_decrypt, METH_VARARGS, nullptr},
    {"crypto_enable_encryption", mod_crypto_enable_encryption, METH_VARARGS, nullptr},
    {"crypto_decrypt_archive_table", mod_crypto_decrypt_archive_table, METH_VARARGS, nullptr},
    {"crypto_decrypt_data", mod_crypto_decrypt_data, METH_VARARGS, nullptr},
    {"crypto_encrypt_archive_table", mod_crypto_encrypt_archive_table, METH_VARARGS, nullptr},
    {"crypto_encrypt_data", mod_crypto_encrypt_data, METH_VARARGS, nullptr},
    {"crypto_magic_mask", mod_crypto_magic_mask, METH_VARARGS, nullptr},
    {"read_rpf_entry", mod_read_rpf_entry, METH_VARARGS, nullptr},
    {"read_rpf_entry_variants", mod_read_rpf_entry_variants, METH_VARARGS, nullptr},
    {"jenk_partial_hash", mod_jenk_partial_hash, METH_VARARGS, nullptr},
    {"jenk_continue_hash", mod_jenk_continue_hash, METH_VARARGS, nullptr},
    {"jenk_finalize_hash", mod_jenk_finalize_hash, METH_VARARGS, nullptr},
    {"jenk_hash", mod_jenk_hash, METH_VARARGS, nullptr},
    {"jenk_hash_many", mod_jenk_hash_many, METH_VARARGS, nullptr},
    {"scan_rpf_batch_into_index", mod_scan_rpf_batch_into_index, METH_VARARGS, nullptr},
    {"scan_rpf_into_index", mod_scan_rpf_into_index, METH_VARARGS, nullptr},
    {"bounds_triangle_area", mod_bounds_triangle_area, METH_VARARGS, nullptr},
    {"bounds_from_vertices", mod_bounds_from_vertices, METH_VARARGS, nullptr},
    {"bounds_sphere_radius_from_vertices", mod_bounds_sphere_radius_from_vertices, METH_VARARGS, nullptr},
    {"bounds_chunk_triangles", mod_bounds_chunk_triangles, METH_VARARGS, nullptr},
    {"bounds_build_octants", mod_bounds_build_octants, METH_VARARGS, nullptr},
    {"bounds_build_bvh", mod_bounds_build_bvh, METH_VARARGS, nullptr},
    {"bounds_quantize_vertices", mod_bounds_quantize_vertices, METH_VARARGS, nullptr},
    {"bounds_indexed_triangle_areas", mod_bounds_indexed_triangle_areas, METH_VARARGS, nullptr},
    {"bounds_collect_triangles", mod_bounds_collect_triangles, METH_VARARGS, nullptr},
    {"ydr_pack_vertex_buffer", mod_ydr_pack_vertex_buffer, METH_VARARGS, nullptr},
    {"ydr_decode_vertex_buffer", mod_ydr_decode_vertex_buffer, METH_VARARGS, nullptr},
    {"ydr_split_mesh_indices", mod_ydr_split_mesh_indices, METH_VARARGS, nullptr},
    {"skin_compose_matrices", mod_skin_compose_matrices, METH_VARARGS, nullptr},
    {"skin_pack_palette_into", mod_skin_pack_palette_into, METH_VARARGS, nullptr},
    {"skin_vertices_into", mod_skin_vertices_into, METH_VARARGS, nullptr},
    {"bounds_decode_polygons", mod_bounds_decode_polygons, METH_VARARGS, nullptr},
    {"bounds_decode_bvh_records", mod_bounds_decode_bvh_records, METH_VARARGS, nullptr},
    {"ynv_decode_edge_list", mod_ynv_decode_edge_list, METH_VARARGS, nullptr},
    {"binary_document_new", mod_binary_document_new, METH_VARARGS, nullptr},
    {"binary_document_size", mod_binary_document_size, METH_VARARGS, nullptr},
    {"binary_document_slice", mod_binary_document_slice, METH_VARARGS, nullptr},
    {"binary_document_c_string", mod_binary_document_c_string, METH_VARARGS, nullptr},
    {"binary_document_read_array", mod_binary_document_read_array, METH_VARARGS, nullptr},
    {"resource_layout_sections", mod_resource_layout_sections, METH_VARARGS, nullptr},
    {"resource_pack_block_sizes", mod_resource_pack_block_sizes, METH_VARARGS, nullptr},
    {"awc_build_peak_values", mod_awc_build_peak_values, METH_VARARGS, nullptr},
    {"awc_split_interleaved_pcm16", mod_awc_split_interleaved_pcm16, METH_VARARGS, nullptr},
    {"awc_interleave_pcm16", mod_awc_interleave_pcm16, METH_VARARGS, nullptr},
    {"awc_decode_adpcm", mod_awc_decode_adpcm, METH_VARARGS, nullptr},
    {"awc_rsxxtea", mod_awc_rsxxtea, METH_VARARGS, nullptr},
    {"awc_parse_pcm_wav", mod_awc_parse_pcm_wav, METH_VARARGS, nullptr},
    {"awc_build_pcm_wav", mod_awc_build_pcm_wav, METH_VARARGS, nullptr},
    {"awc_extract_multichannel_blocks", mod_awc_extract_multichannel_blocks, METH_VARARGS, nullptr},
    {"yed_compile", mod_yed_compile, METH_VARARGS, nullptr},
    {"yed_evaluate", mod_yed_evaluate, METH_VARARGS, nullptr},
    {"ycd_decode_frame_channels", mod_ycd_decode_frame_channels, METH_VARARGS, nullptr},
    {"ycd_encode_frame_channels", mod_ycd_encode_frame_channels, METH_VARARGS, nullptr},
    {"ycd_decode_quantized_values", mod_ycd_decode_quantized_values, METH_VARARGS, nullptr},
    {"ycd_decode_linear_values", mod_ycd_decode_linear_values, METH_VARARGS, nullptr},
    {"vector_interpolate_many", mod_vector_interpolate_many, METH_VARARGS, nullptr},
    {nullptr, nullptr, 0, nullptr},
};

PyModuleDef module_def = {
    PyModuleDef_HEAD_INIT,
    "_native_abi3",
    "Native abi3 backend for fivefury",
    -1,
    module_methods,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};

}  // namespace fivefury_py

PyMODINIT_FUNC PyInit__native_abi3(void) {
    return PyModule_Create(&fivefury_py::module_def);
}
