#include "animation/bindings.h"
#include "audio/bindings.h"
#include "bounds/bindings.h"
#include "crypto/bindings.h"
#include "drawable/bindings.h"
#include "indexing/bindings.h"
#include "resource/bindings.h"
#include "rpf/bindings.h"
#include "spatial/bindings.h"

namespace fivefury_py {

PyMethodDef module_methods[] = {
    {"index_new", guarded_call<mod_index_new>, METH_NOARGS, nullptr},
    {"index_clear", guarded_call<mod_index_clear>, METH_VARARGS, nullptr},
    {"index_count", guarded_call<mod_index_count>, METH_VARARGS, nullptr},
    {"index_add", guarded_call<mod_index_add>, METH_VARARGS, nullptr},
    {"index_find_path_id", guarded_call<mod_index_find_path_id>, METH_VARARGS, nullptr},
    {"index_find_hash_ids", guarded_call<mod_index_find_hash_ids>, METH_VARARGS, nullptr},
    {"index_find_hashes_ids", guarded_call<mod_index_find_hashes_ids>, METH_VARARGS, nullptr},
    {"index_find_kind_ids", guarded_call<mod_index_find_kind_ids>, METH_VARARGS, nullptr},
    {"index_find_container_ids", guarded_call<mod_index_find_container_ids>, METH_VARARGS, nullptr},
    {"index_find_stem_prefix_ids", guarded_call<mod_index_find_stem_prefix_ids>, METH_VARARGS, nullptr},
    {"index_kind_short_hash_map", guarded_call<mod_index_kind_short_hash_map>, METH_VARARGS, nullptr},
    {"index_kind_counts", guarded_call<mod_index_kind_counts>, METH_VARARGS, nullptr},
    {"index_get_path", guarded_call<mod_index_get_path>, METH_VARARGS, nullptr},
    {"index_export_paths", guarded_call<mod_index_export_paths>, METH_VARARGS, nullptr},
    {"index_get_kind", guarded_call<mod_index_get_kind>, METH_VARARGS, nullptr},
    {"index_get_size", guarded_call<mod_index_get_size>, METH_VARARGS, nullptr},
    {"index_get_uncompressed_size", guarded_call<mod_index_get_uncompressed_size>, METH_VARARGS, nullptr},
    {"index_get_flags", guarded_call<mod_index_get_flags>, METH_VARARGS, nullptr},
    {"index_get_archive_encryption", guarded_call<mod_index_get_archive_encryption>, METH_VARARGS, nullptr},
    {"index_get_name_hash", guarded_call<mod_index_get_name_hash>, METH_VARARGS, nullptr},
    {"index_get_short_hash", guarded_call<mod_index_get_short_hash>, METH_VARARGS, nullptr},
    {"index_export_state", guarded_call<mod_index_export_state>, METH_VARARGS, nullptr},
    {"index_import_state", guarded_call<mod_index_import_state>, METH_VARARGS, nullptr},
    {"meta_extract_ytyp_texture_relationships", guarded_call<mod_meta_extract_ytyp_texture_relationships>, METH_VARARGS, nullptr},
    {"texture_index_new", guarded_call<mod_texture_index_new>, METH_NOARGS, nullptr},
    {"texture_index_clear", guarded_call<mod_texture_index_clear>, METH_VARARGS, nullptr},
    {"texture_index_count", guarded_call<mod_texture_index_count>, METH_VARARGS, nullptr},
    {"texture_index_add", guarded_call<mod_texture_index_add>, METH_VARARGS, nullptr},
    {"texture_index_add_many", guarded_call<mod_texture_index_add_many>, METH_VARARGS, nullptr},
    {"texture_index_find_texture", guarded_call<mod_texture_index_find_texture>, METH_VARARGS, nullptr},
    {"texture_index_find_dictionary", guarded_call<mod_texture_index_find_dictionary>, METH_VARARGS, nullptr},
    {"crypto_new", guarded_call<mod_crypto_new>, METH_VARARGS, nullptr},
    {"crypto_can_decrypt", guarded_call<mod_crypto_can_decrypt>, METH_VARARGS, nullptr},
    {"crypto_enable_encryption", guarded_call<mod_crypto_enable_encryption>, METH_VARARGS, nullptr},
    {"crypto_decrypt_archive_table", guarded_call<mod_crypto_decrypt_archive_table>, METH_VARARGS, nullptr},
    {"crypto_decrypt_data", guarded_call<mod_crypto_decrypt_data>, METH_VARARGS, nullptr},
    {"crypto_encrypt_archive_table", guarded_call<mod_crypto_encrypt_archive_table>, METH_VARARGS, nullptr},
    {"crypto_encrypt_data", guarded_call<mod_crypto_encrypt_data>, METH_VARARGS, nullptr},
    {"crypto_magic_mask", guarded_call<mod_crypto_magic_mask>, METH_VARARGS, nullptr},
    {"read_rpf_entry", guarded_call<mod_read_rpf_entry>, METH_VARARGS, nullptr},
    {"rpf_reader_new", guarded_call<mod_rpf_reader_new>, METH_VARARGS, nullptr},
    {"rpf_reader_read", guarded_call<mod_rpf_reader_read>, METH_VARARGS, nullptr},
    {"rpf_reader_table_count", guarded_call<mod_rpf_reader_table_count>, METH_VARARGS, nullptr},
    {"read_rpf_entry_variants", guarded_call<mod_read_rpf_entry_variants>, METH_VARARGS, nullptr},
    {"jenk_partial_hash", guarded_call<mod_jenk_partial_hash>, METH_VARARGS, nullptr},
    {"jenk_continue_hash", guarded_call<mod_jenk_continue_hash>, METH_VARARGS, nullptr},
    {"jenk_finalize_hash", guarded_call<mod_jenk_finalize_hash>, METH_VARARGS, nullptr},
    {"jenk_hash", guarded_call<mod_jenk_hash>, METH_VARARGS, nullptr},
    {"jenk_hash_many", guarded_call<mod_jenk_hash_many>, METH_VARARGS, nullptr},
    {"scan_rpf_batch_into_index", guarded_call<mod_scan_rpf_batch_into_index>, METH_VARARGS, nullptr},
    {"scan_rpf_into_index", guarded_call<mod_scan_rpf_into_index>, METH_VARARGS, nullptr},
    {"bounds_triangle_area", guarded_call<mod_bounds_triangle_area>, METH_VARARGS, nullptr},
    {"bounds_from_vertices", guarded_call<mod_bounds_from_vertices>, METH_VARARGS, nullptr},
    {"bounds_sphere_radius_from_vertices", guarded_call<mod_bounds_sphere_radius_from_vertices>, METH_VARARGS, nullptr},
    {"bounds_chunk_triangles", guarded_call<mod_bounds_chunk_triangles>, METH_VARARGS, nullptr},
    {"bounds_build_octants", guarded_call<mod_bounds_build_octants>, METH_VARARGS, nullptr},
    {"bounds_build_bvh", guarded_call<mod_bounds_build_bvh>, METH_VARARGS, nullptr},
    {"bounds_quantize_vertices", guarded_call<mod_bounds_quantize_vertices>, METH_VARARGS, nullptr},
    {"bounds_indexed_triangle_areas", guarded_call<mod_bounds_indexed_triangle_areas>, METH_VARARGS, nullptr},
    {"bounds_collect_triangles", guarded_call<mod_bounds_collect_triangles>, METH_VARARGS, nullptr},
    {"ydr_pack_vertex_buffer", guarded_call<mod_ydr_pack_vertex_buffer>, METH_VARARGS, nullptr},
    {"ydr_decode_vertex_buffer", guarded_call<mod_ydr_decode_vertex_buffer>, METH_VARARGS, nullptr},
    {"ydr_split_mesh_indices", guarded_call<mod_ydr_split_mesh_indices>, METH_VARARGS, nullptr},
    {"skin_compose_matrices", guarded_call<mod_skin_compose_matrices>, METH_VARARGS, nullptr},
    {"skin_pack_palette_into", guarded_call<mod_skin_pack_palette_into>, METH_VARARGS, nullptr},
    {"skin_vertices_into", guarded_call<mod_skin_vertices_into>, METH_VARARGS, nullptr},
    {"bounds_decode_polygons", guarded_call<mod_bounds_decode_polygons>, METH_VARARGS, nullptr},
    {"bounds_decode_bvh_records", guarded_call<mod_bounds_decode_bvh_records>, METH_VARARGS, nullptr},
    {"ynv_decode_edge_list", guarded_call<mod_ynv_decode_edge_list>, METH_VARARGS, nullptr},
    {"binary_document_new", guarded_call<mod_binary_document_new>, METH_VARARGS, nullptr},
    {"binary_document_size", guarded_call<mod_binary_document_size>, METH_VARARGS, nullptr},
    {"binary_document_slice", guarded_call<mod_binary_document_slice>, METH_VARARGS, nullptr},
    {"binary_document_c_string", guarded_call<mod_binary_document_c_string>, METH_VARARGS, nullptr},
    {"binary_document_read_array", guarded_call<mod_binary_document_read_array>, METH_VARARGS, nullptr},
    {"resource_layout_sections", guarded_call<mod_resource_layout_sections>, METH_VARARGS, nullptr},
    {"resource_pack_block_sizes", guarded_call<mod_resource_pack_block_sizes>, METH_VARARGS, nullptr},
    {"awc_build_peak_values", guarded_call<mod_awc_build_peak_values>, METH_VARARGS, nullptr},
    {"awc_split_interleaved_pcm16", guarded_call<mod_awc_split_interleaved_pcm16>, METH_VARARGS, nullptr},
    {"awc_interleave_pcm16", guarded_call<mod_awc_interleave_pcm16>, METH_VARARGS, nullptr},
    {"awc_decode_adpcm", guarded_call<mod_awc_decode_adpcm>, METH_VARARGS, nullptr},
    {"awc_rsxxtea", guarded_call<mod_awc_rsxxtea>, METH_VARARGS, nullptr},
    {"awc_parse_pcm_wav", guarded_call<mod_awc_parse_pcm_wav>, METH_VARARGS, nullptr},
    {"awc_build_pcm_wav", guarded_call<mod_awc_build_pcm_wav>, METH_VARARGS, nullptr},
    {"awc_extract_multichannel_blocks", guarded_call<mod_awc_extract_multichannel_blocks>, METH_VARARGS, nullptr},
    {"yed_compile", guarded_call<mod_yed_compile>, METH_VARARGS, nullptr},
    {"yed_evaluate", guarded_call<mod_yed_evaluate>, METH_VARARGS, nullptr},
    {"ycd_decode_frame_channels", guarded_call<mod_ycd_decode_frame_channels>, METH_VARARGS, nullptr},
    {"ycd_encode_frame_channels", guarded_call<mod_ycd_encode_frame_channels>, METH_VARARGS, nullptr},
    {"ycd_decode_quantized_values", guarded_call<mod_ycd_decode_quantized_values>, METH_VARARGS, nullptr},
    {"ycd_decode_linear_values", guarded_call<mod_ycd_decode_linear_values>, METH_VARARGS, nullptr},
    {"ycd_track_sampler_new", guarded_call<mod_ycd_track_sampler_new>, METH_VARARGS, nullptr},
    {"ycd_track_sampler_window", guarded_call<mod_ycd_track_sampler_window>, METH_VARARGS, nullptr},
    {"ycd_track_sampler_retained_count", guarded_call<mod_ycd_track_sampler_retained_count>, METH_VARARGS, nullptr},
    {"vector_interpolate_many", guarded_call<mod_vector_interpolate_many>, METH_VARARGS, nullptr},
    {nullptr, nullptr, 0, nullptr},
};

PyModuleDef module_def = {
    PyModuleDef_HEAD_INIT,
    "_native_abi3",
    "Native abi3 backend for fivefury",
    -1,
    module_methods,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
};

}  // namespace fivefury_py

PyMODINIT_FUNC PyInit__native_abi3(void) {
    return PyModule_Create(&fivefury_py::module_def);
}
