from ..map_extensions import (
    AudioCollisionSettingsExtension,
    AudioEmitterExtension,
    BuoyancyExtension,
    CapsuleBoundDef,
    ClimbHandHoldExtension,
    DecalExtension,
    DoorExtension,
    ExplosionEffectExtension,
    ExpressionExtension,
    LadderExtension,
    LightAttrDef,
    LightEffectExtension,
    LightExtension,
    LightShaftExtension,
    ParticleEffectExtension,
    ProcObjectExtension,
    ScriptChildExtension,
    ScriptExtension,
    ScrollbarsExtension,
    SpawnPointExtension,
    SpawnPointOverrideExtension,
    SwayableEffectExtension,
    VerletClothCustomBoundsExtension,
    WalkDontWalkExtension,
    WindDisturbanceExtension,
)
from .base import BlockDesc, ContainerLodDef, PhysicsDictionary
from .cargens import CarGen, CarGenerator
from .defs import YMAP_ENUM_INFOS, YMAP_STRUCT_INFOS
from .entities import EntityDef, MloInstanceDef
from .enums import (
    YmapCarGenFlags,
    YmapContentFlags,
    YmapEntityFlags,
    YmapFlags,
    YmapLodLevel,
    YmapLodLightCategory,
    YmapLodLightType,
    YmapMloInstanceFlags,
    YmapPriorityLevel,
)
from .grass import (
    Aabb,
    GrassBatch,
    GrassInstance,
    GrassInstanceBatch,
    InstancedData,
    InstancedMapData,
)
from .io import read_ymap, save_ymap
from .lights import (
    MAX_LOD_LIGHT_CAPSULE_EXTENT,
    MAX_LOD_LIGHT_CONE_ANGLE,
    MAX_LOD_LIGHT_CORONA_INTENSITY,
    MAX_LOD_LIGHT_INTENSITY,
    DistantLodLights,
    DistantLodLightsSoa,
    LodLight,
    LodLights,
    LodLightsSoa,
)
from .lodlight_generation import (
    GeneratedLodLight,
    calculate_light_physical_bounds,
    calculate_lod_light_category,
    calculate_lod_light_hash,
    extract_lod_light,
    extract_lod_lights,
    validate_lod_light_source_bounds,
)
from .model import Ymap
from .occluders import AngleMode, BoxOccluder, OccludeModel
from .timecycle import TimeCycleModifier

Entity = EntityDef
MloInstance = MloInstanceDef
Block = BlockDesc

__all__ = [
    "MAX_LOD_LIGHT_CAPSULE_EXTENT",
    "MAX_LOD_LIGHT_CONE_ANGLE",
    "MAX_LOD_LIGHT_CORONA_INTENSITY",
    "MAX_LOD_LIGHT_INTENSITY",
    "YMAP_ENUM_INFOS",
    "YMAP_STRUCT_INFOS",
    "Aabb",
    "AngleMode",
    "AudioCollisionSettingsExtension",
    "AudioEmitterExtension",
    "Block",
    "BlockDesc",
    "BoxOccluder",
    "BuoyancyExtension",
    "CapsuleBoundDef",
    "CarGen",
    "CarGenerator",
    "ClimbHandHoldExtension",
    "ContainerLodDef",
    "DecalExtension",
    "DistantLodLights",
    "DistantLodLightsSoa",
    "DoorExtension",
    "Entity",
    "EntityDef",
    "ExplosionEffectExtension",
    "ExpressionExtension",
    "GeneratedLodLight",
    "GrassBatch",
    "GrassInstance",
    "GrassInstanceBatch",
    "InstancedData",
    "InstancedMapData",
    "LadderExtension",
    "LightAttrDef",
    "LightEffectExtension",
    "LightExtension",
    "LightShaftExtension",
    "LodLight",
    "LodLights",
    "LodLightsSoa",
    "MloInstance",
    "MloInstanceDef",
    "OccludeModel",
    "ParticleEffectExtension",
    "PhysicsDictionary",
    "ProcObjectExtension",
    "ScriptChildExtension",
    "ScriptExtension",
    "ScrollbarsExtension",
    "SpawnPointExtension",
    "SpawnPointOverrideExtension",
    "SwayableEffectExtension",
    "TimeCycleModifier",
    "VerletClothCustomBoundsExtension",
    "WalkDontWalkExtension",
    "WindDisturbanceExtension",
    "Ymap",
    "YmapCarGenFlags",
    "YmapContentFlags",
    "YmapEntityFlags",
    "YmapFlags",
    "YmapLodLevel",
    "YmapLodLightCategory",
    "YmapLodLightType",
    "YmapMloInstanceFlags",
    "YmapPriorityLevel",
    "calculate_light_physical_bounds",
    "calculate_lod_light_category",
    "calculate_lod_light_hash",
    "extract_lod_light",
    "extract_lod_lights",
    "read_ymap",
    "save_ymap",
    "validate_lod_light_source_bounds",
]
