from __future__ import annotations

from .sequence_channels import (
    YcdAnimChannel,
    YcdAnimSequence,
    YcdCachedQuaternionChannel,
    YcdChannelType,
    YcdIndirectQuantizeFloatChannel,
    YcdLinearFloatChannel,
    YcdQuantizeFloatChannel,
    YcdRawFloatChannel,
    YcdSequenceRootChannelRef,
    YcdStaticFloatChannel,
    YcdStaticQuaternionChannel,
    YcdStaticVector3Channel,
    channel_frame_bits,
)
from .sequence_codec import build_sequence_data, parse_sequence_data
from .sequence_tracks import (
    CAMERA_TRACK_IDS,
    FACIAL_TRACK_IDS,
    ROOT_MOTION_TRACK_IDS,
    YcdAnimationTrack,
    get_ycd_track_name,
    is_ycd_camera_track,
    is_ycd_facial_track,
    is_ycd_object_track,
    is_ycd_position_track,
    is_ycd_rotation_track,
    is_ycd_root_motion_track,
    is_ycd_uv_track,
)

__all__ = [
    "YcdAnimationTrack",
    "YcdChannelType",
    "CAMERA_TRACK_IDS",
    "ROOT_MOTION_TRACK_IDS",
    "FACIAL_TRACK_IDS",
    "YcdAnimChannel",
    "YcdAnimSequence",
    "YcdCachedQuaternionChannel",
    "YcdIndirectQuantizeFloatChannel",
    "YcdLinearFloatChannel",
    "YcdQuantizeFloatChannel",
    "YcdRawFloatChannel",
    "YcdSequenceRootChannelRef",
    "YcdStaticFloatChannel",
    "YcdStaticQuaternionChannel",
    "YcdStaticVector3Channel",
    "build_sequence_data",
    "channel_frame_bits",
    "get_ycd_track_name",
    "is_ycd_camera_track",
    "is_ycd_facial_track",
    "is_ycd_object_track",
    "is_ycd_position_track",
    "is_ycd_rotation_track",
    "is_ycd_root_motion_track",
    "is_ycd_uv_track",
    "parse_sequence_data",
]
