from __future__ import annotations

DAT_VIRTUAL_BASE = 0x50000000
BOUNDING_SPHERE_OFFSET = 0x20
MAIN_DRAWABLE_POINTER_OFFSET = 0x30
DRAWABLE_ARRAY_POINTER_OFFSET = 0x38
DRAWABLE_NAMES_POINTER_OFFSET = 0x40
DRAWABLE_ARRAY_COUNT_OFFSET = 0x48
DAMAGED_DRAWABLE_INDEX_OFFSET = 0x4C
ROOT_CHILD_POINTER_OFFSET = 0x50
TUNE_NAME_POINTER_OFFSET = 0x58
ENV_CLOTH_ARRAY_OFFSET = 0x60
CHAR_CLOTH_ARRAY_OFFSET = 0x70
USER_DATA_POINTER_OFFSET = 0x80
COLLISION_EVENT_SET_POINTER_OFFSET = 0x88
COLLISION_EVENT_PLAYER_POINTER_OFFSET = 0x90
SHARED_MATRIX_SET_POINTER_OFFSET = 0xA8
ESTIMATED_CACHE_SIZE_OFFSET = 0xB0
ESTIMATED_ARTICULATED_CACHE_SIZE_OFFSET = 0xB8
GLASS_PANE_MODEL_INFOS_POINTER_OFFSET = 0xE0
PHYSICS_LOD_GROUP_POINTER_OFFSET = 0xF0
CLOTH_DRAWABLE_POINTER_OFFSET = 0xF8
LIGHT_ATTRIBUTES_ARRAY_OFFSET = 0x110
VEHICLE_GLASS_WINDOWS_POINTER_OFFSET = 0x120
DRAWABLE_FIELDS_OFFSET = 0x10
PHYSICS_LOD_GROUP_FIELDS_OFFSET = 0x10
PHYSICS_LOD_MIN_SIZE = 0x11F
FRAGMENT_ROOT_SIZE = 0x130
FRAGMENT_DRAWABLE_SIZE = 0x150
FRAGMENT_DRAWABLE_BASE_OFFSET = 0x10
FRAGMENT_DRAWABLE_TAIL_OFFSET = 0xA8

RAW_FIELD_LABELS = {
    0x08: "resource_pages",
    0x30: "common_drawable",
    0x38: "extra_drawables",
    0x40: "extra_drawable_names",
    0x50: "root_child",
    0x58: "tune_name",
    0x60: "environment_cloth",
    0x70: "character_cloth",
    0x80: "user_data",
    0x88: "collision_event_set",
    0x90: "collision_event_player",
    0xA8: "shared_matrix_set",
    0xE0: "glass_pane_model_infos",
    0xF0: "physics_lod_group",
    0xF8: "cloth_drawable",
    0x110: "light_attributes",
    0x120: "vehicle_glass_windows",
}

__all__ = [
    "BOUNDING_SPHERE_OFFSET",
    "CHAR_CLOTH_ARRAY_OFFSET",
    "CLOTH_DRAWABLE_POINTER_OFFSET",
    "COLLISION_EVENT_PLAYER_POINTER_OFFSET",
    "COLLISION_EVENT_SET_POINTER_OFFSET",
    "DAMAGED_DRAWABLE_INDEX_OFFSET",
    "DAT_VIRTUAL_BASE",
    "DRAWABLE_ARRAY_COUNT_OFFSET",
    "DRAWABLE_ARRAY_POINTER_OFFSET",
    "DRAWABLE_FIELDS_OFFSET",
    "DRAWABLE_NAMES_POINTER_OFFSET",
    "ENV_CLOTH_ARRAY_OFFSET",
    "ESTIMATED_ARTICULATED_CACHE_SIZE_OFFSET",
    "ESTIMATED_CACHE_SIZE_OFFSET",
    "FRAGMENT_DRAWABLE_BASE_OFFSET",
    "FRAGMENT_DRAWABLE_SIZE",
    "FRAGMENT_DRAWABLE_TAIL_OFFSET",
    "FRAGMENT_ROOT_SIZE",
    "GLASS_PANE_MODEL_INFOS_POINTER_OFFSET",
    "LIGHT_ATTRIBUTES_ARRAY_OFFSET",
    "MAIN_DRAWABLE_POINTER_OFFSET",
    "PHYSICS_LOD_GROUP_FIELDS_OFFSET",
    "PHYSICS_LOD_GROUP_POINTER_OFFSET",
    "PHYSICS_LOD_MIN_SIZE",
    "RAW_FIELD_LABELS",
    "ROOT_CHILD_POINTER_OFFSET",
    "SHARED_MATRIX_SET_POINTER_OFFSET",
    "TUNE_NAME_POINTER_OFFSET",
    "USER_DATA_POINTER_OFFSET",
    "VEHICLE_GLASS_WINDOWS_POINTER_OFFSET",
]
