from __future__ import annotations

DAT_VIRTUAL_BASE = 0x50000000
BOUNDING_SPHERE_OFFSET = 0x20
MAIN_DRAWABLE_POINTER_OFFSET = 0x30
DRAWABLE_ARRAY_POINTER_OFFSET = 0x38
DRAWABLE_NAMES_POINTER_OFFSET = 0x40
DRAWABLE_ARRAY_COUNT_OFFSET = 0x48
DAMAGED_DRAWABLE_POINTER_OFFSET = 0x50
ROOT_CHILD_POINTER_OFFSET = 0x58
TUNE_NAME_POINTER_OFFSET = 0x60
PHYSICS_LOD_GROUP_POINTER_OFFSET = 0xF0
CLOTH_DRAWABLE_POINTER_OFFSET = 0xF8
DRAWABLE_FIELDS_OFFSET = 0x10
PHYSICS_LOD_GROUP_FIELDS_OFFSET = 0x10
PHYSICS_LOD_MIN_SIZE = 0x11F

RAW_FIELD_LABELS = {
    0x08: "resource_pages",
    0x30: "common_drawable",
    0x38: "extra_drawables",
    0x40: "extra_drawable_names",
    0x50: "damaged_drawable",
    0x58: "root_child",
    0x60: "tune_name",
    0xA8: "env_or_char_cloth_data",
    0xF0: "physics_lod_group",
    0xF8: "cloth_drawable",
}

__all__ = [
    "BOUNDING_SPHERE_OFFSET",
    "CLOTH_DRAWABLE_POINTER_OFFSET",
    "DAMAGED_DRAWABLE_POINTER_OFFSET",
    "DAT_VIRTUAL_BASE",
    "DRAWABLE_ARRAY_COUNT_OFFSET",
    "DRAWABLE_ARRAY_POINTER_OFFSET",
    "DRAWABLE_FIELDS_OFFSET",
    "DRAWABLE_NAMES_POINTER_OFFSET",
    "MAIN_DRAWABLE_POINTER_OFFSET",
    "PHYSICS_LOD_GROUP_FIELDS_OFFSET",
    "PHYSICS_LOD_GROUP_POINTER_OFFSET",
    "PHYSICS_LOD_MIN_SIZE",
    "RAW_FIELD_LABELS",
    "ROOT_CHILD_POINTER_OFFSET",
    "TUNE_NAME_POINTER_OFFSET",
]
