from __future__ import annotations

from ..meta import MetaStructInfo
from ..meta.defs import MetaDataType, meta_name
from ..ymap.defs import _arrayinfo, _entry, _enum_info


YTYP_STRUCT_INFOS = [
    MetaStructInfo(
        name_hash=meta_name("CBaseArchetypeDef"),
        key=2411387556,
        unknown=1024,
        structure_size=144,
        entries=[
            _entry("lodDist", 8, MetaDataType.FLOAT),
            _entry("flags", 12, MetaDataType.UNSIGNED_INT),
            _entry("specialAttribute", 16, MetaDataType.UNSIGNED_INT),
            _entry("bbMin", 32, MetaDataType.FLOAT_XYZ),
            _entry("bbMax", 48, MetaDataType.FLOAT_XYZ),
            _entry("bsCentre", 64, MetaDataType.FLOAT_XYZ),
            _entry("bsRadius", 80, MetaDataType.FLOAT),
            _entry("hdTextureDist", 84, MetaDataType.FLOAT),
            _entry("name", 88, MetaDataType.HASH),
            _entry("textureDictionary", 92, MetaDataType.HASH),
            _entry("clipDictionary", 96, MetaDataType.HASH),
            _entry("drawableDictionary", 100, MetaDataType.HASH),
            _entry("physicsDictionary", 104, MetaDataType.HASH),
            _entry("assetType", 108, MetaDataType.INT_ENUM, ref_key="rage__fwArchetypeDef__eAssetType"),
            _entry("assetName", 112, MetaDataType.HASH),
            _arrayinfo(MetaDataType.STRUCTURE_POINTER),
            _entry("extensions", 120, MetaDataType.ARRAY, ref_index=15),
        ],
    ),
    MetaStructInfo(
        name_hash=meta_name("CTimeArchetypeDef"),
        key=2520619910,
        unknown=1024,
        structure_size=160,
        entries=[
            _entry("lodDist", 8, MetaDataType.FLOAT),
            _entry("flags", 12, MetaDataType.UNSIGNED_INT),
            _entry("specialAttribute", 16, MetaDataType.UNSIGNED_INT),
            _entry("bbMin", 32, MetaDataType.FLOAT_XYZ),
            _entry("bbMax", 48, MetaDataType.FLOAT_XYZ),
            _entry("bsCentre", 64, MetaDataType.FLOAT_XYZ),
            _entry("bsRadius", 80, MetaDataType.FLOAT),
            _entry("hdTextureDist", 84, MetaDataType.FLOAT),
            _entry("name", 88, MetaDataType.HASH),
            _entry("textureDictionary", 92, MetaDataType.HASH),
            _entry("clipDictionary", 96, MetaDataType.HASH),
            _entry("drawableDictionary", 100, MetaDataType.HASH),
            _entry("physicsDictionary", 104, MetaDataType.HASH),
            _entry("assetType", 108, MetaDataType.INT_ENUM, ref_key="rage__fwArchetypeDef__eAssetType"),
            _entry("assetName", 112, MetaDataType.HASH),
            _arrayinfo(MetaDataType.STRUCTURE_POINTER),
            _entry("extensions", 120, MetaDataType.ARRAY, ref_index=15),
            _entry("timeFlags", 144, MetaDataType.UNSIGNED_INT),
        ],
    ),
    MetaStructInfo(
        name_hash=meta_name("CMloRoomDef"),
        key=3885428245,
        unknown=1024,
        structure_size=112,
        entries=[
            _entry("name", 8, MetaDataType.CHAR_POINTER),
            _entry("bbMin", 32, MetaDataType.FLOAT_XYZ),
            _entry("bbMax", 48, MetaDataType.FLOAT_XYZ),
            _entry("blend", 64, MetaDataType.FLOAT),
            _entry("timecycleName", 68, MetaDataType.HASH),
            _entry("secondaryTimecycleName", 72, MetaDataType.HASH),
            _entry("flags", 76, MetaDataType.UNSIGNED_INT),
            _entry("portalCount", 80, MetaDataType.UNSIGNED_INT),
            _entry("floorId", 84, MetaDataType.SIGNED_INT),
            _entry("exteriorVisibiltyDepth", 88, MetaDataType.SIGNED_INT),
            _arrayinfo(MetaDataType.UNSIGNED_INT),
            _entry("attachedObjects", 96, MetaDataType.ARRAY, ref_index=10),
        ],
    ),
    MetaStructInfo(
        name_hash=meta_name("CMloPortalDef"),
        key=1110221513,
        unknown=768,
        structure_size=64,
        entries=[
            _entry("roomFrom", 8, MetaDataType.UNSIGNED_INT),
            _entry("roomTo", 12, MetaDataType.UNSIGNED_INT),
            _entry("flags", 16, MetaDataType.UNSIGNED_INT),
            _entry("mirrorPriority", 20, MetaDataType.UNSIGNED_INT),
            _entry("opacity", 24, MetaDataType.UNSIGNED_INT),
            _entry("audioOcclusion", 28, MetaDataType.UNSIGNED_INT),
            _arrayinfo(MetaDataType.FLOAT_XYZ),
            _entry("corners", 32, MetaDataType.ARRAY, ref_index=6),
            _arrayinfo(MetaDataType.UNSIGNED_INT),
            _entry("attachedObjects", 48, MetaDataType.ARRAY, ref_index=8),
        ],
    ),
    MetaStructInfo(
        name_hash=meta_name("CMloEntitySet"),
        key=4180211587,
        unknown=768,
        structure_size=48,
        entries=[
            _entry("name", 8, MetaDataType.HASH),
            _arrayinfo(MetaDataType.UNSIGNED_INT),
            _entry("locations", 16, MetaDataType.ARRAY, ref_index=1),
            _arrayinfo(MetaDataType.STRUCTURE_POINTER),
            _entry("entities", 32, MetaDataType.ARRAY, ref_index=3),
        ],
    ),
    MetaStructInfo(
        name_hash=meta_name("CMloTimeCycleModifier"),
        key=838874674,
        unknown=1024,
        structure_size=48,
        entries=[
            _entry("name", 8, MetaDataType.HASH),
            _entry("sphere", 16, MetaDataType.FLOAT_XYZW),
            _entry("percentage", 32, MetaDataType.FLOAT),
            _entry("range", 36, MetaDataType.FLOAT),
            _entry("startHour", 40, MetaDataType.UNSIGNED_INT),
            _entry("endHour", 44, MetaDataType.UNSIGNED_INT),
        ],
    ),
    MetaStructInfo(
        name_hash=meta_name("CMloArchetypeDef"),
        key=937664754,
        unknown=1024,
        structure_size=240,
        entries=[
            _entry("lodDist", 8, MetaDataType.FLOAT),
            _entry("flags", 12, MetaDataType.UNSIGNED_INT),
            _entry("specialAttribute", 16, MetaDataType.UNSIGNED_INT),
            _entry("bbMin", 32, MetaDataType.FLOAT_XYZ),
            _entry("bbMax", 48, MetaDataType.FLOAT_XYZ),
            _entry("bsCentre", 64, MetaDataType.FLOAT_XYZ),
            _entry("bsRadius", 80, MetaDataType.FLOAT),
            _entry("hdTextureDist", 84, MetaDataType.FLOAT),
            _entry("name", 88, MetaDataType.HASH),
            _entry("textureDictionary", 92, MetaDataType.HASH),
            _entry("clipDictionary", 96, MetaDataType.HASH),
            _entry("drawableDictionary", 100, MetaDataType.HASH),
            _entry("physicsDictionary", 104, MetaDataType.HASH),
            _entry("assetType", 108, MetaDataType.INT_ENUM, ref_key="rage__fwArchetypeDef__eAssetType"),
            _entry("assetName", 112, MetaDataType.HASH),
            _arrayinfo(MetaDataType.STRUCTURE_POINTER),
            _entry("extensions", 120, MetaDataType.ARRAY, ref_index=15),
            _entry("mloFlags", 144, MetaDataType.UNSIGNED_INT),
            _arrayinfo(MetaDataType.STRUCTURE_POINTER),
            _entry("entities", 152, MetaDataType.ARRAY, ref_index=18),
            _arrayinfo(MetaDataType.STRUCTURE, ref_key="CMloRoomDef"),
            _entry("rooms", 168, MetaDataType.ARRAY, ref_index=20),
            _arrayinfo(MetaDataType.STRUCTURE, ref_key="CMloPortalDef"),
            _entry("portals", 184, MetaDataType.ARRAY, ref_index=22),
            _arrayinfo(MetaDataType.STRUCTURE, ref_key="CMloEntitySet"),
            _entry("entitySets", 200, MetaDataType.ARRAY, ref_index=24),
            _arrayinfo(MetaDataType.STRUCTURE, ref_key="CMloTimeCycleModifier"),
            _entry("timeCycleModifiers", 216, MetaDataType.ARRAY, ref_index=26),
        ],
    ),
    MetaStructInfo(
        name_hash=meta_name("CMapTypes"),
        key=2608875220,
        unknown=768,
        structure_size=80,
        entries=[
            _arrayinfo(MetaDataType.STRUCTURE_POINTER),
            _entry("extensions", 8, MetaDataType.ARRAY, ref_index=0),
            _arrayinfo(MetaDataType.STRUCTURE_POINTER),
            _entry("archetypes", 24, MetaDataType.ARRAY, ref_index=2),
            _entry("name", 40, MetaDataType.HASH),
            _arrayinfo(MetaDataType.HASH),
            _entry("dependencies", 48, MetaDataType.ARRAY, ref_index=5),
            _arrayinfo(MetaDataType.STRUCTURE, ref_key="CCompositeEntityType"),
            _entry("compositeEntityTypes", 64, MetaDataType.ARRAY, ref_index=7),
        ],
    ),
]

YTYP_ENUM_INFOS = [
    _enum_info("rage__fwArchetypeDef__eAssetType"),
    _enum_info("rage__eLodType"),
    _enum_info("rage__ePriorityLevel"),
    _enum_info("CExtensionDefLadderMaterialType"),
    _enum_info("CExtensionDefLightShaftDensityType"),
    _enum_info("CExtensionDefLightShaftVolumeType"),
]
